### PR TITLE
Fix multiple issues with Shadowmeld and Elusiveness

### LINKED ISSUE #74: Spell - Shadowmeld (Night Elf Racial)
**Description:**

Shadowmeld has a few minor fixes needed.
(https://wow.gamepedia.com/Shadowmeld)

**Current behaviour:**

Shadowmeld does not remove combat immediately.
Shadowmeld does not wait for the cooldown to start while still in Shadowmeld.
Shadowmelded players can be seen from an unusually long distance.
[NEW]: Shadowmeld allows druid feral abilities that normally require Prowling to be casted while Shadowmelded.

**Expected behaviour:**

Shadowmeld should properly remove combat while fighting.
Shadowmeld should not begin it's cooldown until the player exits Shadowmeld.
Shadowmeld should not be seen beyond 10-12 yards. (Tested)
[NEW]: Shadowmeld should not let druid be able to cast 'Ravage' and 'Pounce'.

**Steps to reproduce the problem:**

1. Create a night elf character.
2. Create another character.
2. Duel each other and cast Shadowmeld on the night elf
4. Stand ontop of the player and slowly move away.
5. [NEW]: Cast Shadowmeld while in melee range of another character. [Druid only]

**TC rev. hash/commit:** 
TrinityCore rev. d0c7bbab40bc

**TDB version:**  
434.20021

**Operating system:** 
Win 10 (x64)

### PR DESCRIPTION
**Pull request by AGandrup**
**Changes proposed**:

- Druids can no longer use their Pounce and Ravage spells in Shadowmeld
- Elusiveness now decreases the distance from which one can be seen while shadowmelded.
- Elusiveness now increases speed by 5% for Rogues while stealthed. (Note: Druids Prowl spell is not affected by this, which is blizzlike).

**Issues addressed**: 

- Fixes #74 

**Tests performed**: 

- Builds
- Tested in game, works as intended.

**Known issues and TODO list**:

- None

### CODE REVIEW

File: src/server/scripts/Spells/spell_generic.cpp [hunk 1]
```diff
@@ -5447,6 +5447,49 @@ class spell_gen_face_rage : public AuraScript
...
+            int32 basepoints0 = aurEff->GetAmount();
+            StealthType type = StealthType(aurEff->GetMiscValue());
+            caster->m_stealth.AddValue(type, basepoints0);
+        }
+    }
+
+    void OnRemove(AuraEffect const* /*effect*/, AuraEffectHandleModes /*mode*/)
+    {
+        Unit* caster = GetCaster();
+
```
Comment (Ovahlord) [inline src/server/scripts/Spells/spell_generic.cpp:5478]: this is a hack. Shadowmeld uses a stealth aura effect which you can manipulate by using the OnEffectCalcValue hook. There you can add the value of dummy effect to the already calculated value

File: src/server/scripts/Spells/spell_rogue.cpp [hunk 2]
```diff
@@ -880,10 +882,26 @@ class spell_rog_stealth : public SpellScriptLoader
                     target->CastSpell(target, SPELL_ROGUE_OVERKILL_PERIODIC, true);
             }
 
+            void HandleSpeedIncrease(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/) {
+
```
Comment (Ovahlord) [inline src/server/scripts/Spells/spell_rogue.cpp:886]: same here. CalcValue. Whenever you use  SetSpeed, it's most likely a hack because these helpers are only meant to be used by internals.

File: src/server/scripts/Spells/spell_generic.cpp (hunk 1 above)
Comment (AGandrup) [reply src/server/scripts/Spells/spell_generic.cpp:5478]: Hmm, so I have to do something like
`spellInfo->Effects[EFFECT_2].CalcValue(GetCaster(), basepoints0);` ?

Comment (Ovahlord) [reply src/server/scripts/Spells/spell_generic.cpp:5478]: https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/6e412b16de04d7cd9ef7efa8b75b5ffd87db70f7 something like this.

File: src/server/scripts/Spells/spell_generic.cpp [hunk 3]
```diff
@@ -5466,9 +5466,7 @@ class spell_gen_shadowmeld : public AuraScript {
 
         if (AuraEffect const* aurEff = caster->GetAuraEffect(SPELL_RACIAL_ELUSIVENESS, EFFECT_0)) {
```
Comment (Ovahlord) [inline src/server/scripts/Spells/spell_generic.cpp:5467]: remove the brackets. Also we don't inline brackets here, they always go into a new line. Brackets are only used for more than one action inside of conditions.

File: sql/updates/world/4.3.4/2022_04_10_01_world.sql [hunk 4]
```diff
@@ -0,0 +1,3 @@
+DELETE FROM `conditions` WHERE `ConditionTypeOrReference`=1 AND `ConditionValue1`=58984;
+INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES (17, 0, 6785, 0, 0, 1, 0, 58984, 0, 0, 1, 0, 0, '', 'Druid - Ravage cannot be used while Shadowmeld is active');
+INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES (17, 0, 9005, 0, 0, 1, 0, 58984, 0, 0, 1, 0, 0, '', 'Druid - Pounce cannot be used while Shadowmeld is active');
```
Comment (Ovahlord) [inline sql/updates/world/4.3.4/2022_04_10_01_world.sql:3]: Get rid of these and move them to SpellScript, using the CheckCast handling.  Also don't use  single inserts for multiple entries, merge them all into one insert query. Like here:  https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/blob/master/sql/updates/world/4.3.4/2022_03_10_01_world.sql

File: src/server/game/Spells/SpellMgr.cpp [hunk 5]
```diff
@@ -5944,6 +5944,11 @@ void SpellMgr::LoadSpellInfoCorrections()
         spellInfo->AttributesEx |= SPELL_ATTR1_FINISHING_MOVE_DURATION;
     });
 
+    // Shadowmeld
```
Comment (Ovahlord) [inline src/server/game/Spells/SpellMgr.cpp:5947]: that one is wrong. The cooldown is being triggered on start since 3.0.3. Remove it

File: sql/updates/world/4.3.4/2022_04_12_00_world.sql [hunk 6]
```diff
@@ -0,0 +1,3 @@
+DELETE FROM `spell_script_names` WHERE `ScriptName`= 'spell_dru_pounce' OR `ScriptName`= 'spell_dru_ravage';
```
Comment (Ovahlord) [inline sql/updates/world/4.3.4/2022_04_12_00_world.sql:1]: Put that into the other sql file. No need to split them

File: src/server/game/Spells/SpellMgr.cpp (hunk 5 above)
Comment (AGandrup) [reply src/server/game/Spells/SpellMgr.cpp]: Good catch. Guess I am too used to Classic 😛
